### ISSUE TITLE
try to identify phonetic values of tones in original source

### ISSUE THREAD

**Issue by LinguList** [lexibank/castrosui#1]
Tones are displayed phonologically, so the numbers can't be accepted, etc.

**Comment by xrotwang** [comment]
@LinguList do we have to do this for CLICS 3?

**Comment by LinguList** [comment]
no, for later, however, it'll be important

**Comment by SimonGreenhill** [comment]
@tresoldi -- can you look at this one please?

**Comment by LinguList** [comment]
Please leave it to me, as this is my baby dataset.

**Comment by LinguList** [comment]
It's tricky: how do we make clear tone should not be interpreted phonetically. I guess it is either really doing this, or discarding the dataset for inclusion in lexibank. Or deleting tonal contrasts for now. Let me reflect.

**Comment by LinguList** [comment]
I have now checked the orthoprofiles. It seems straightforward to just handle this on the basis per ortho profile. I can do it, but it may need a week or so, doing one per day.

**Comment by LinguList** [comment]
First example with language-indivudual orthoprofiles has been pushed now.

**Comment by FredericBlum** [comment]
Perfect, thank you for taking care of this. We have no specific hurry, so a week or two is absolutely fine with us

**Comment by LinguList** [comment]
done now. There is are certain allophones of tones 7 and 8 that I cannot handle, but the tone is marked before the slash, and I just took the first value (normally for short vowels), so I consider this as good enough for now.
